language: python
python:
  - '2.7'
node_js:
  - '6'
branches:
  only:
    - /^v[.].*$/
install:
  - pip install -r requirements.txt
  - nvm install 6
  - npm install
script: grunt
before_deploy:
  - openssl aes-256-cbc -K $encrypted_8961825fb73e_key -iv $encrypted_8961825fb73e_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/django-project -p 3901 jason@healthycookingfortoday.com:/home/django/
  on:
    tags: true
